apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentelemetry-collector-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: opentelemetry-collector