apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: opentelemetry-collector
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
  - port: telemetry
    interval: 30s
    path: /metrics