apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "k8s-workload-identity-sa@{{ .Values.projectId }}.iam.gserviceaccount.com"