apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: opentelemetry-collector