apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinity.nodeAffinity.required.key }}
                operator: In
                values:
                {{- range .Values.affinity.nodeAffinity.required.values }}
                - {{ . }}
                {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: {{ .Values.affinity.nodeAffinity.preferred.weight }}
            preference:
              matchExpressions:
              - key: {{ .Values.affinity.nodeAffinity.preferred.key }}
                operator: In
                values:
                {{- range .Values.affinity.nodeAffinity.preferred.values }}
                - {{ . }}
                {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ .Values.affinity.podAntiAffinity.key }}
                operator: In
                values:
                {{- range .Values.affinity.podAntiAffinity.values }}
                - {{ . }}
                {{- end }}
            topologyKey: {{ .Values.affinity.podAntiAffinity.topologyKey }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          args:
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}