apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-dns-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns