apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "k8s-workload-identity-sa@{{ .Values.project_id}}.iam.gserviceaccount.com"
  labels:
    app.kubernetes.io/name: {{ .Values.namespace }}
