apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Values.namespace }}
data:
  server.properties: |
    # KRaft mode settings
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@kafka-0.kafka-headless.kafka.svc.cluster.local:9093
    
    # Listeners
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    inter.broker.listener.name=PLAINTEXT
    controller.listener.names=CONTROLLER
    advertised.listeners=PLAINTEXT://kafka-0.kafka-headless.kafka.svc.cluster.local:9092
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    
    # Logs and storage
    log.dirs=/var/lib/kafka/data
    num.partitions=3
    default.replication.factor=1
    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    min.insync.replicas=1
    
    # Other settings
    group.initial.rebalance.delay.ms=0
    auto.create.topics.enable=true


