apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: kafka-monitoring
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.namespace }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics