apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: kafka-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: kafka-role
  apiGroup: rbac.authorization.k8s.io