apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.namespace }}
spec:
  ports:
  - port: 9092
    name: broker
    targetPort: 9092
  selector:
    app: {{ .Values.namespace }}
---
# Headless Service for Kafka
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.namespace }}
spec:
  ports:
  - port: 9092
    name: broker
  - port: 9093
    name: controller
  clusterIP: None
  selector:
    app: {{ .Values.namespace }}