apiVersion: batch/v1
kind: Job
metadata:
  name: create-topics
  namespace: {{ .Values.namespace }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: kafka-sa
      containers:
      - name: kafka-client
        image: confluentinc/cp-kafka:7.4.0
        command:
        - /bin/bash
        - -c
        - |
          # Wait for Kafka to be ready
          sleep 30
          # Create test topic
          kafka-topics --bootstrap-server kafka-headless.kafka.svc.cluster.local:9092 --create --topic gcs-topic --partitions 1 --replication-factor 1
          kafka-topics --bootstrap-server kafka-headless.kafka.svc.cluster.local:9092 --create --topic pinecone-topic --partitions 1 --replication-factor 1 
          echo "Both Topics created successfully"
      restartPolicy: Never
  backoffLimit: 3