apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
  - port: 9187
    path: /metrics
    interval: 30s