apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webapp-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: web-ssl
  issuerRef:
    name:  {{ .Values.certmanagertype }}
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: {{ .Values.hostname }}
  dnsNames:
    - {{ .Values.hostname }}