apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certmanagertype }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.letsencryptserver }}
    email: {{ .Values.letsencryptemail }}
    privateKeySecretRef:
      name: {{ .Values.certmanagertype }}
    solvers:
    - http01:
        ingress:
          class: istio