apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app: cert-manager
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  endpoints:
  - port: 9402
    path: /metrics
    interval: 30s
  targetLabels:
    metadata:
    - pod
    - container