apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pinecone-key
  namespace: {{ .Values.namespace_trace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store-trace
    kind: SecretStore
  target:
    name: pinecone-key
    creationPolicy: Owner
  data:
  - secretKey: PINECONE_KEY
    remoteRef:
      key: pineconeapi-key

