apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store-trace
  namespace: {{ .Values.namespace_trace }}
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterLocation }}
          clusterName: {{ .Values.clusterName }}
          serviceAccountRef:
            name: {{ .Values.serviceAccountName_trace }}
            namespace: {{ .Values.namespace_trace }}
      projectID: {{ .Values.project_id }}
