apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterLocation }}
          clusterName: {{ .Values.clusterName }}
          serviceAccountRef:
            name: {{ .Values.serviceAccountName }}
            namespace: {{ .Values.namespace }}
      projectID: {{ .Values.project_id }}
