apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-rolebinding
  namespace: {{ .Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: postgres-sa
    namespace: {{ .Values.namespace}}
roleRef:
  kind: Role
  name: postgres-role
  apiGroup: rbac.authorization.k8s.io