apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - a
                      - b
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - a
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - c
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: chatbot-frontend
          image: {{ .Values.frontend.image }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pgrep -f app.py"
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pgrep -f app.py"
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: RAG_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: rag-api-url
                  key: RAG_API_BASE_URL
          ports:
            - containerPort: 8501
