apiVersion: v1
kind: Service
metadata:
  name: chatbot-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: chatbot-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: ClusterIP