apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-pdf-consumer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pdf-consumer
  template:
    metadata:
      labels:
        app: kafka-pdf-consumer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - a
                      - b
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - a
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: pool
                    operator: In
                    values:
                      - c
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: trace-sa
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: kafka-pdf-consumer
          image: {{ .Values.consumer.image }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "pgrep -f kafka_pdf_consumer.py"
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "pgrep -f kafka_pdf_consumer.py"
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: PINECONE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: PINECONE_ENVIRONMENT
            - name: PINECONE_INDEX
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: PINECONE_INDEX
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_TOPIC_NAME
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: KAFKA_TOPIC_NAME
            - name: LOCAL_PDF_DIR
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: LOCAL_PDF_DIR
            - name: KAFKA_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: app-config
                  key: KAFKA_GROUP_ID
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password-secret
                  key: DB_PASSWORD
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pinecone-key
                  key: PINECONE_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openapi-key
                  key: OPENAPI_KEY
