apiVersion: v1
kind: ServiceAccount
metadata:
  name: trace-sa
  namespace: {{ .Values.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: "k8s-workload-identity-sa@{{ .Values.project_id}}.iam.gserviceaccount.com"
automountServiceAccountToken: false
