apiVersion: v1
kind: Secret
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.appConfig.db.name | quote }}
  DB_USER: {{ .Values.appConfig.db.user | quote }}
  DB_HOST: {{ .Values.appConfig.db.host | quote }}
  DB_PORT: {{ .Values.appConfig.db.port | quote }}
  PINECONE_ENVIRONMENT: {{ .Values.appConfig.pinecone.environment | quote }}
  PINECONE_INDEX: {{ .Values.appConfig.pinecone.index | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.appConfig.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC_NAME: {{ .Values.appConfig.kafka.topicName | quote }}
  LOCAL_PDF_DIR: {{ .Values.appConfig.localPdfDir | quote }}
  KAFKA_GROUP_ID: {{ .Values.appConfig.kafka.groupId | quote }}
  PROJECT_ID: {{ .Values.project_id | quote }}
  GCS_SUBSCRIPTION: {{ .Values.appConfig.kafka.gcs_subscription| quote }}