apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: trace-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.gateway.host }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{ .Values.virtualService.destinationHost }}
            port:
              number: {{ .Values.virtualService.destinationPort }}
