apiVersion: v1
kind: Service
metadata:
  name: go-webapp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: go-webapp
  ports:
    - protocol: TCP
      port: {{ .Values.goApp.servicePort }}
      targetPort: {{ .Values.goApp.targetPort }}
  type: ClusterIP

