apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.goApp.secret.DB_HOST | b64enc | quote }}
  DB_PORT: {{ .Values.goApp.secret.DB_PORT | b64enc | quote }}
  DB_USER: {{ .Values.goApp.secret.DB_USER | b64enc | quote }}
  DB_NAME: {{ .Values.goApp.secret.DB_NAME | b64enc | quote }}
  GCS_BUCKET_NAME: {{ .Values.GCS_BUCKET_NAME | b64enc | quote }}

