apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: istio-monitoring
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: 15014
    path: /metrics
    interval: 30s