apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-app-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints","secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "create", "delete"]
