apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: go-webapp
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.hostname }}
  gateways:
    - go-webapp-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: go-webapp
            port:
              number: 80